### ISSUE TITLE
Fortran compilation error on Windows

### ISSUE THREAD

**Issue by marcobels** [pvthinker/Fluid2d#5]
Sorry, i have problems running the code. If you have some time could you try to help me to fix this problem. I attached the error, which basically occurs when my fortran compiler tries to run fortran_advection.f90.  The final output is: "fatal error LNK1112". Any ideas?
![Cattura](https://user-images.githubusercontent.com/52315438/60336901-e9a1f300-99a1-11e9-9f9c-73d547e46ceb.JPG)

**Comment by pvthinker** [comment]
Hello marcobels,
I'd love to help but on that one I'm really stuck. The error msg warns about a conflict between x86 and x64 extension. It suggests that the problem is on the compiler side, not on Fluid2d. Have you tried to do a 'f2py' on a simple Fortran subroutine?
Fluid2d does run on windows.
Cheers,
Guillaume

**Comment by marcobels** [comment]
Sure it is, but i can't find it. Meanwhile I can open your matlab version.
It's an incredible work! Is it updated and revised like the python versione?

Il giorno ven 28 giu 2019 alle ore 14:39 Guillaume Roullet <
notifications@github.com> ha scritto:

**Comment by pvthinker** [comment]
Hi marcobels,
Thanks for the compliment. I stopped maintaining the Matlab years ago. If you like it, you'll love the python version, it's so much better.
Meanwhile, I found [this on stackoverflow](https://stackoverflow.com/questions/47105737/python-module-with-fortran-lnk1112-module-machine-type-x86-conflicts-with-ta).  It looks relevant. Hope it helps.
Cheers,
Guillaume
